/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-users': CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-users': CmsUser;
    exams: Exam;
    questions: Question;
    concepts: Concept;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cms-users': CmsUsersSelect<false> | CmsUsersSelect<true>;
    exams: ExamsSelect<false> | ExamsSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    concepts: ConceptsSelect<false> | ConceptsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ko' | 'en') | ('ko' | 'en')[];
  globals: {
    'site-config': SiteConfig;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
  };
  locale: 'ko' | 'en';
  user: CmsUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * better-auth 세션 미러 — 직접 만들지 않는다. 접근 부여는 user.role 에 admin|author 지정.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
  id: number;
  /**
   * better-auth "user".id
   */
  authUserId: string;
  email: string;
  name?: string | null;
  /**
   * better-auth user.role 스냅샷 — 세션이 진실
   */
  role: 'admin' | 'author';
  updatedAt: string;
  createdAt: string;
  collection: 'cms-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exams".
 */
export interface Exam {
  id: number;
  /**
   * 예: aws
   */
  provider: string;
  /**
   * 예: saa-c03
   */
  slug: string;
  /**
   * provider/slug 파생 — 기존 exam_key 스코프와 동일
   */
  examKey?: string | null;
  providerName: string;
  /**
   * 예: SAA-C03
   */
  code: string;
  name: string;
  /**
   * 문제집의 기본 표시 언어(meta.language)
   */
  language: 'ko' | 'en';
  /**
   * 이모지 — 이미지 아이콘은 iconImage(둘 다 있으면 이미지 우선)
   */
  icon?: string | null;
  iconImage?: (number | null) | Media;
  /**
   * 자격 계열 안정 id, 예: aws-solutions-architect — 없으면 provider 로 그룹핑
   */
  trackId?: string | null;
  /**
   * 자격 계열 표시명
   */
  trackName?: string | null;
  /**
   * diagrams.json 원형
   */
  diagrams?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * q2svc.json 원형 — qn → svc[]
   */
  q2svc?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * icons.json 원형 — svc → 아이콘
   */
  svcIcons?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: number;
  exam: number | Exam;
  /**
   * 문항 번호 — 문제집 내 유일
   */
  qn: number;
  /**
   * 예: 📦 스토리지
   */
  topic?: string | null;
  /**
   * 지문 — **굵게** 마크업 허용(현행 렌더러 규칙)
   */
  q: string;
  /**
   * 보기 — key(A,B,…)는 언어 무관, text 만 언어별
   */
  options: {
    key: string;
    text: string;
    id?: string | null;
  }[];
  /**
   * 정답 key 목록 — 보기 key 의 부분집합(예: A / A,C)
   */
  answer: string[];
  explanation?: string | null;
  tip?: string | null;
  /**
   * 덤프 문서 페이지 번호
   */
  page?: number | null;
  /**
   * 원문 딥링크(예: marginnote4app://…)
   */
  deeplink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concepts".
 */
export interface Concept {
  id: number;
  exam: number | Exam;
  /**
   * 서비스/개념 식별자 — q2svc 조인 키(언어 무관), 예: Amazon S3 스토리지 클래스
   */
  svc: string;
  /**
   * 목록 순서 — 편집으로 재배열되지 않게 명시 보관(0003 ord 계승)
   */
  ord: number;
  /**
   * 분류, 예: 스토리지
   */
  cat?: string | null;
  /**
   * 축약 표기, 예: S3 Classes
   */
  abbr?: string | null;
  /**
   * 정의
   */
  deff: string;
  /**
   * 핵심 포인트
   */
  key?: string | null;
  /**
   * 언제 쓰나
   */
  when?: string | null;
  /**
   * 함정
   */
  trap?: string | null;
  /**
   * 비교
   */
  vs?: string | null;
  /**
   * 상세(선택)
   */
  detail?: string | null;
  /**
   * 비용 특성(선택)
   */
  cost?: string | null;
  /**
   * 관련 문항 번호(표시분)
   */
  rel?: number[] | null;
  /**
   * 관련 문항 총 개수
   */
  reln?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cms-users';
        value: number | CmsUser;
      } | null)
    | ({
        relationTo: 'exams';
        value: number | Exam;
      } | null)
    | ({
        relationTo: 'questions';
        value: number | Question;
      } | null)
    | ({
        relationTo: 'concepts';
        value: number | Concept;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  authUserId?: T;
  email?: T;
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exams_select".
 */
export interface ExamsSelect<T extends boolean = true> {
  provider?: T;
  slug?: T;
  examKey?: T;
  providerName?: T;
  code?: T;
  name?: T;
  language?: T;
  icon?: T;
  iconImage?: T;
  trackId?: T;
  trackName?: T;
  diagrams?: T;
  q2svc?: T;
  svcIcons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  exam?: T;
  qn?: T;
  topic?: T;
  q?: T;
  options?:
    | T
    | {
        key?: T;
        text?: T;
        id?: T;
      };
  answer?: T;
  explanation?: T;
  tip?: T;
  page?: T;
  deeplink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concepts_select".
 */
export interface ConceptsSelect<T extends boolean = true> {
  exam?: T;
  svc?: T;
  ord?: T;
  cat?: T;
  abbr?: T;
  deff?: T;
  key?: T;
  when?: T;
  trap?: T;
  vs?: T;
  detail?: T;
  cost?: T;
  rel?: T;
  reln?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * 홈 문구·공지 배너 — 저장 즉시 사이트에 반영된다
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  /**
   * 홈 상단 한 줄 소개 — 비우면 기본 문구
   */
  tagline?: string | null;
  /**
   * 홈 하단 — 비우면 기본 문구
   */
  footerText?: string | null;
  notice?: {
    enabled?: boolean | null;
    text?: string | null;
    tone?: ('info' | 'warning') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  tagline?: T;
  footerText?: T;
  notice?:
    | T
    | {
        enabled?: T;
        text?: T;
        tone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}