apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - backup-cronjob.yaml
images:
  - name: ghcr.io/young1ll/quizdeck-wp
    newTag: sha-d0e59b5
